#!/bin/bash
# BlackRoad Automated Pull Request Generator
# Automatically creates PRs for dependency updates, refactorings, and more
# Version: 1.0.0

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
PURPLE='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

# Configuration
PROJECTS_DIR="${PROJECTS_DIR:-$HOME/projects}"
PR_DB="$HOME/.blackroad/auto-pr/prs.db"

# Initialize database
init_db() {
    mkdir -p "$(dirname "$PR_DB")"

    sqlite3 "$PR_DB" <<'SQL'
CREATE TABLE IF NOT EXISTS pull_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    repo TEXT NOT NULL,
    branch_name TEXT NOT NULL,
    pr_number INTEGER,
    pr_url TEXT,
    title TEXT NOT NULL,
    description TEXT,
    pr_type TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    merged_at TEXT,
    agent_id TEXT
);

CREATE TABLE IF NOT EXISTS pr_changes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pr_id INTEGER,
    file_path TEXT NOT NULL,
    change_type TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    FOREIGN KEY (pr_id) REFERENCES pull_requests(id)
);

CREATE INDEX IF NOT EXISTS idx_pr_repo ON pull_requests(repo);
CREATE INDEX IF NOT EXISTS idx_pr_status ON pull_requests(status);
SQL

    echo -e "${GREEN}[AUTO-PR]${NC} Database initialized!"
}

# Create PR for dependency updates
create_dependency_update_pr() {
    local repo_path="$1"
    local repo_name="$(basename "$repo_path")"

    echo -e "${BOLD}${CYAN}━━━ Creating Dependency Update PR for $repo_name ━━━${NC}"

    cd "$repo_path"

    # Check if there are any changes
    if ! git diff --quiet; then
        echo -e "${YELLOW}  Found dependency changes!${NC}"

        # Create branch
        local branch_name="deps/auto-update-$(date +%Y%m%d-%H%M%S)"
        git checkout -b "$branch_name" 2>/dev/null || true

        # Commit changes
        local commit_msg="chore: Auto-update dependencies

Automated dependency updates via BlackRoad Auto-PR system.

Updated packages:
$(git diff --name-only | sed 's/^/- /')

🤖 Generated with [BlackRoad Auto-PR](https://github.com/BlackRoad-OS)

Co-Authored-By: Claude <noreply@anthropic.com>"

        git add -A
        git commit -m "$commit_msg" 2>/dev/null || echo "  No changes to commit"

        # Push to remote
        if git remote get-url origin &>/dev/null; then
            echo -e "${CYAN}  Pushing to remote...${NC}"
            git push -u origin "$branch_name" 2>&1 | grep -v "warning:" || true

            # Create PR using gh CLI
            if command -v gh &> /dev/null; then
                echo -e "${CYAN}  Creating pull request...${NC}"

                local pr_body="## 📦 Automated Dependency Updates

This PR contains automated dependency updates for \`$repo_name\`.

### Changes
- Updated npm/pip/Go packages to latest compatible versions
- Security vulnerabilities addressed (if any)
- No breaking changes expected

### Testing
- [ ] Run test suite
- [ ] Verify application still works
- [ ] Check for deprecation warnings

### Generated By
🤖 BlackRoad Auto-PR System
🔗 Part of BlackRoad Coordination v2.0

---

**Auto-merge:** This PR can be safely auto-merged after tests pass.

Co-Authored-By: Claude <noreply@anthropic.com>"

                local pr_url=$(gh pr create \
                    --title "chore: Auto-update dependencies ($(date +%Y-%m-%d))" \
                    --body "$pr_body" \
                    --label "dependencies,automated" \
                    2>&1 | grep -o 'https://.*' || echo "")

                if [ -n "$pr_url" ]; then
                    echo -e "${GREEN}  ✓ PR created: $pr_url${NC}"

                    # Log to database
                    sqlite3 "$PR_DB" <<SQL
INSERT INTO pull_requests (repo, branch_name, pr_url, title, pr_type, status, agent_id)
VALUES ('$repo_name', '$branch_name', '$pr_url', 'Auto-update dependencies', 'dependency_update', 'created', '${MY_CLAUDE:-unknown}');
SQL

                    # Log to memory
                    if [ -f ~/memory-system.sh ]; then
                        ~/memory-system.sh log created "auto-pr-$repo_name" "Created automated dependency update PR for $repo_name: $pr_url" "pr,automation,dependencies" 2>/dev/null || true
                    fi
                else
                    echo -e "${YELLOW}  ⚠ Could not create PR (may need authentication)${NC}"
                fi
            else
                echo -e "${YELLOW}  ⚠ gh CLI not found, cannot create PR${NC}"
            fi
        else
            echo -e "${YELLOW}  ⚠ No remote origin configured${NC}"
        fi

        # Switch back to main/master
        git checkout main 2>/dev/null || git checkout master 2>/dev/null || true
    else
        echo -e "${GREEN}  ✓ No dependency updates needed${NC}"
    fi

    echo ""
}

# Create PR for all repos with dependency updates
create_all_dependency_prs() {
    echo -e "${BOLD}${PURPLE}╔════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${PURPLE}║                                                        ║${NC}"
    echo -e "${BOLD}${PURPLE}║   🤖 AUTOMATED DEPENDENCY UPDATE PR GENERATOR 🤖       ║${NC}"
    echo -e "${BOLD}${PURPLE}║                                                        ║${NC}"
    echo -e "${BOLD}${PURPLE}╚════════════════════════════════════════════════════════╝${NC}"
    echo ""

    local total_prs=0

    # First, run dependency updater
    echo -e "${CYAN}Step 1/2: Updating dependencies across all repos...${NC}"
    if [ -f ~/blackroad-dependency-updater.sh ]; then
        ~/blackroad-dependency-updater.sh update-all 2>/dev/null || true
    fi

    echo ""
    echo -e "${CYAN}Step 2/2: Creating pull requests for repos with changes...${NC}"
    echo ""

    if [ -d "$PROJECTS_DIR" ]; then
        find "$PROJECTS_DIR" -name ".git" -type d 2>/dev/null | while read -r git_dir; do
            local repo_path=$(dirname "$git_dir")

            if create_dependency_update_pr "$repo_path"; then
                ((total_prs++))
            fi
        done
    fi

    echo -e "${GREEN}━━━ PR Generation Complete ━━━${NC}"
    echo -e "${CYAN}Total PRs created:${NC} Check database for count"
    echo ""
}

# Create PR for a refactoring operation
create_refactoring_pr() {
    local repo_path="$1"
    local operation="$2"
    local description="$3"

    local repo_name="$(basename "$repo_path")"

    echo -e "${CYAN}Creating refactoring PR for $repo_name...${NC}"

    cd "$repo_path"

    if ! git diff --quiet; then
        local branch_name="refactor/auto-$operation-$(date +%Y%m%d-%H%M%S)"
        git checkout -b "$branch_name" 2>/dev/null || true

        local commit_msg="refactor: $description

Automated refactoring via BlackRoad Auto-PR system.

🤖 Generated with [BlackRoad Auto-PR](https://github.com/BlackRoad-OS)

Co-Authored-By: Claude <noreply@anthropic.com>"

        git add -A
        git commit -m "$commit_msg" 2>/dev/null || true

        if git remote get-url origin &>/dev/null; then
            git push -u origin "$branch_name" 2>&1 | grep -v "warning:" || true

            if command -v gh &> /dev/null; then
                local pr_body="## 🔧 Automated Refactoring

**Operation:** $operation
**Description:** $description

### Changes
This PR contains automated refactoring changes across the codebase.

### Testing
- [ ] Run test suite
- [ ] Verify no functionality broken
- [ ] Code review

### Generated By
🤖 BlackRoad Auto-PR System

Co-Authored-By: Claude <noreply@anthropic.com>"

                local pr_url=$(gh pr create \
                    --title "refactor: $description" \
                    --body "$pr_body" \
                    --label "refactoring,automated" \
                    2>&1 | grep -o 'https://.*' || echo "")

                if [ -n "$pr_url" ]; then
                    echo -e "${GREEN}  ✓ PR created: $pr_url${NC}"

                    sqlite3 "$PR_DB" <<SQL
INSERT INTO pull_requests (repo, branch_name, pr_url, title, pr_type, status, agent_id)
VALUES ('$repo_name', '$branch_name', '$pr_url', '$description', 'refactoring', 'created', '${MY_CLAUDE:-unknown}');
SQL
                fi
            fi
        fi

        git checkout main 2>/dev/null || git checkout master 2>/dev/null || true
    fi
}

# Show PR statistics
show_stats() {
    echo -e "${CYAN}━━━ Automated PR Statistics ━━━${NC}"
    echo ""

    if [ -f "$PR_DB" ]; then
        echo -e "${PURPLE}Total PRs Created:${NC}"
        sqlite3 -column "$PR_DB" "
            SELECT
                pr_type,
                COUNT(*) as total,
                SUM(CASE WHEN status='created' THEN 1 ELSE 0 END) as open,
                SUM(CASE WHEN status='merged' THEN 1 ELSE 0 END) as merged
            FROM pull_requests
            GROUP BY pr_type;
        " 2>/dev/null || echo "No data"

        echo ""
        echo -e "${PURPLE}Recent PRs:${NC}"
        sqlite3 -column "$PR_DB" "
            SELECT
                substr(repo, 1, 30) as repository,
                substr(title, 1, 40) as title,
                status,
                substr(created_at, 1, 10) as created
            FROM pull_requests
            ORDER BY created_at DESC
            LIMIT 15;
        " 2>/dev/null || echo "No recent PRs"
    else
        echo "No PR database found"
    fi

    echo ""
}

# List all created PRs
list_prs() {
    local status="${1:-all}"

    echo -e "${CYAN}━━━ Automated Pull Requests ━━━${NC}"
    echo ""

    if [ -f "$PR_DB" ]; then
        local where_clause=""
        if [ "$status" != "all" ]; then
            where_clause="WHERE status='$status'"
        fi

        sqlite3 -column "$PR_DB" "
            SELECT
                id,
                repo,
                substr(title, 1, 50) as title,
                status,
                pr_url
            FROM pull_requests
            $where_clause
            ORDER BY created_at DESC;
        " 2>/dev/null || echo "No PRs found"
    fi

    echo ""
}

# Auto-merge PRs that pass tests
auto_merge_safe_prs() {
    echo -e "${BOLD}${GREEN}━━━ Auto-Merge Safe PRs ━━━${NC}"
    echo ""

    if [ ! -f "$PR_DB" ]; then
        echo "No PR database found"
        return
    fi

    # Get PRs that are safe to auto-merge
    sqlite3 "$PR_DB" "SELECT repo, pr_url FROM pull_requests WHERE status='created' AND pr_type='dependency_update';" 2>/dev/null | \
    while IFS='|' read -r repo pr_url; do
        if [ -n "$pr_url" ]; then
            echo -e "${CYAN}Checking PR for $repo...${NC}"

            # Extract PR number from URL
            local pr_num=$(echo "$pr_url" | grep -o '[0-9]*$')

            if command -v gh &> /dev/null && [ -n "$pr_num" ]; then
                # Check if tests passed
                local checks_status=$(gh pr checks "$pr_num" --json state -q '.[] | .state' 2>/dev/null || echo "PENDING")

                if echo "$checks_status" | grep -q "SUCCESS"; then
                    echo -e "${GREEN}  ✓ Tests passed! Auto-merging...${NC}"

                    gh pr merge "$pr_num" --auto --squash --delete-branch 2>/dev/null && \
                        sqlite3 "$PR_DB" "UPDATE pull_requests SET status='merged', merged_at=CURRENT_TIMESTAMP WHERE pr_url='$pr_url';" || \
                        echo -e "${YELLOW}  ⚠ Could not auto-merge${NC}"
                else
                    echo -e "${YELLOW}  ⏳ Tests still running or failed${NC}"
                fi
            fi
        fi
    done

    echo ""
}

# Show help
show_help() {
    cat <<EOF
${CYAN}BlackRoad Automated Pull Request Generator${NC}

Automatically creates pull requests for dependency updates, refactorings, and more.

USAGE:
    blackroad-auto-pr-generator.sh <command>

COMMANDS:
    init                    Initialize PR database
    create-dep-prs          Create PRs for dependency updates in all repos
    create-refactor-pr      Create PR for refactoring operation
    stats                   Show PR statistics
    list [status]           List all PRs (optional: filter by status)
    auto-merge              Auto-merge safe PRs that pass tests
    help                    Show this help

EXAMPLES:
    # Initialize
    blackroad-auto-pr-generator.sh init

    # Create dependency update PRs for all repos
    blackroad-auto-pr-generator.sh create-dep-prs

    # View statistics
    blackroad-auto-pr-generator.sh stats

    # List open PRs
    blackroad-auto-pr-generator.sh list created

    # Auto-merge safe PRs
    blackroad-auto-pr-generator.sh auto-merge

FEATURES:
    ✓ Automatic PR creation for dependency updates
    ✓ Automatic PR creation for refactoring operations
    ✓ GitHub CLI integration
    ✓ Auto-merge safe PRs when tests pass
    ✓ PR tracking in database
    ✓ Memory system integration
    ✓ Coordination-aware

REQUIREMENTS:
    - gh CLI (GitHub CLI) installed and authenticated
    - Git configured with remote origins
    - Write access to repositories

DATABASE: $PR_DB
EOF
}

# Main
main() {
    local cmd="${1:-help}"

    case "$cmd" in
        init)
            init_db
            ;;
        create-dep-prs)
            init_db
            create_all_dependency_prs
            ;;
        create-refactor-pr)
            init_db
            create_refactoring_pr "$2" "$3" "$4"
            ;;
        stats)
            show_stats
            ;;
        list)
            list_prs "$2"
            ;;
        auto-merge)
            auto_merge_safe_prs
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            echo -e "${RED}[AUTO-PR]${NC} Unknown command: $cmd"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
